name: nfd
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - scikit-image
  - scikit-learn
  - matplotlib
  - pillow
  - imageio
  - tqdm
  - pyyaml
  - networkx
  - trimesh
  - mrcfile
  - plyfile
  - tifffile
  - mpi4py
  - mpich
